---
title: "cross_validation"
author: "Huili Zheng"
date: "11/18/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(mgcv)
```

## simulate a dataset

```{r}
set.seed(1)
nonlin_df = 
  tibble(
    id = 1:100,
    x = runif(100, 0, 1),
    y = 1 - 10 * (x - .3) ^ 2 + rnorm(100, 0, .3)
  )

nonlin_df %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point()
```

create splites by hand; plot; fit some models

```{r}
train_df = sample_n(nonlin_df, 80)
test_df = anti_join(nonlin_df,train_df, by = "id")

ggplot(train_df, aes(x = x, y = y)) +
  geom_point() +
  geom_point(data = test_df, color = 'red')
```

fit my models:

```{r}
linear_model = lm(y~x, data = train_df)
smooth_mod = mgcv::gam(y ~ s(x), data = train_df)
wiggly_mod = mgcv::gam(y ~ s(x, k = 30), sp = 10e-6, data = train_df)
```

plot the results

```{r}
train_df %>%
  add_predictions(smooth_mod) %>%
  ggplot(aes(x = x, y = y)) +
  geom_point() +
  geom_line(aes(y = pred))

train_df %>%
  add_predictions(wiggly_mod) %>%
  ggplot(aes(x = x, y = y)) +
  geom_point() +
  geom_line(aes(y = pred))
```

quantify the results
```{r}
rmse(linear_model, test_df)
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)
```

## cv iteratively

use 'modelr::crossv_mc'.

```{r}
cv_df = 
  crossv_mc(nonlin_df,100) %>%
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )

cv_df %>% pull(train) %>% .[[1]] %>% as_tibble()
```

let's fit some models...
```{r}
cv_df = 
  cv_df %>%
  mutate(
    linear_mod = map(.x = train, ~lm(y ~ x, data = .x)),
    smooth_mod = map(.x = train, ~gam(y ~ s(x),data = .x)),
    wiggly_mod = map(.x = train, ~gam(y ~ s(x, k = 30), sp = 10e-6, data = .x))
  ) %>%
  mutate(
    rmse_linear = map2_dbl(.x = linear_mod, .y = test, ~rmse(model = .x, data = .y)),
    rmse_smooth = map2_dbl(.x = smooth_mod, .y = test, ~rmse(model = .x, data = .y)),
    rmse_wiggly = map2_dbl(.x = wiggly_mod, .y = test, ~rmse(model = .x, data = .y))
  )
```

Look at output

```{r}
cv_df %>%
  select(.id, starts_with("rmse")) %>%
  pivot_longer(rmse_linear:rmse_wiggly, names_to = "model", values_to = "rmse", names_prefix = "rmse") %>%
  ggplot(aes(x = model, y = rmse)) +
  geom_boxplot()
```

